// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/tick_tock/v1/tick_tock.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskDefineStatus int32

const (
	TaskDefineStatus_TASK_DEFINE_STATUS_UNSPECIFIED TaskDefineStatus = 0
	TaskDefineStatus_TASK_DEFINE_STATUS_ENABLE      TaskDefineStatus = 1
	TaskDefineStatus_TASK_DEFINE_STATUS_DISABLE     TaskDefineStatus = 2
)

// Enum value maps for TaskDefineStatus.
var (
	TaskDefineStatus_name = map[int32]string{
		0: "TASK_DEFINE_STATUS_UNSPECIFIED",
		1: "TASK_DEFINE_STATUS_ENABLE",
		2: "TASK_DEFINE_STATUS_DISABLE",
	}
	TaskDefineStatus_value = map[string]int32{
		"TASK_DEFINE_STATUS_UNSPECIFIED": 0,
		"TASK_DEFINE_STATUS_ENABLE":      1,
		"TASK_DEFINE_STATUS_DISABLE":     2,
	}
)

func (x TaskDefineStatus) Enum() *TaskDefineStatus {
	p := new(TaskDefineStatus)
	*p = x
	return p
}

func (x TaskDefineStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskDefineStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_tick_tock_v1_tick_tock_proto_enumTypes[0].Descriptor()
}

func (TaskDefineStatus) Type() protoreflect.EnumType {
	return &file_api_tick_tock_v1_tick_tock_proto_enumTypes[0]
}

func (x TaskDefineStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskDefineStatus.Descriptor instead.
func (TaskDefineStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_tick_tock_v1_tick_tock_proto_rawDescGZIP(), []int{0}
}

type CreateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	App              string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CronExpression   string                 `protobuf:"bytes,3,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	NotifyHttpParams *Notify                `protobuf:"bytes,4,opt,name=notify_http_params,json=notifyHttpParams,proto3" json:"notify_http_params,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_tick_tock_v1_tick_tock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tick_tock_v1_tick_tock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_tick_tock_v1_tick_tock_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *CreateRequest) GetNotifyHttpParams() *Notify {
	if x != nil {
		return x.NotifyHttpParams
	}
	return nil
}

type Notify struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HttpUrl          string                 `protobuf:"bytes,1,opt,name=http_url,json=httpUrl,proto3" json:"http_url,omitempty"`
	HttpMethod       string                 `protobuf:"bytes,2,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	HttpHeaderParams map[string]string      `protobuf:"bytes,3,rep,name=http_header_params,json=httpHeaderParams,proto3" json:"http_header_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HttpBodyParams   string                 `protobuf:"bytes,4,opt,name=http_body_params,json=httpBodyParams,proto3" json:"http_body_params,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Notify) Reset() {
	*x = Notify{}
	mi := &file_api_tick_tock_v1_tick_tock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify) ProtoMessage() {}

func (x *Notify) ProtoReflect() protoreflect.Message {
	mi := &file_api_tick_tock_v1_tick_tock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify.ProtoReflect.Descriptor instead.
func (*Notify) Descriptor() ([]byte, []int) {
	return file_api_tick_tock_v1_tick_tock_proto_rawDescGZIP(), []int{1}
}

func (x *Notify) GetHttpUrl() string {
	if x != nil {
		return x.HttpUrl
	}
	return ""
}

func (x *Notify) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *Notify) GetHttpHeaderParams() map[string]string {
	if x != nil {
		return x.HttpHeaderParams
	}
	return nil
}

func (x *Notify) GetHttpBodyParams() string {
	if x != nil {
		return x.HttpBodyParams
	}
	return ""
}

type CreateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TaskDefineReplyData   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReply) Reset() {
	*x = CreateReply{}
	mi := &file_api_tick_tock_v1_tick_tock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReply) ProtoMessage() {}

func (x *CreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_tick_tock_v1_tick_tock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReply.ProtoReflect.Descriptor instead.
func (*CreateReply) Descriptor() ([]byte, []int) {
	return file_api_tick_tock_v1_tick_tock_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateReply) GetData() *TaskDefineReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TaskDefineReplyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tid           string                 `protobuf:"bytes,1,opt,name=tid,proto3" json:"tid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDefineReplyData) Reset() {
	*x = TaskDefineReplyData{}
	mi := &file_api_tick_tock_v1_tick_tock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDefineReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDefineReplyData) ProtoMessage() {}

func (x *TaskDefineReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_api_tick_tock_v1_tick_tock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDefineReplyData.ProtoReflect.Descriptor instead.
func (*TaskDefineReplyData) Descriptor() ([]byte, []int) {
	return file_api_tick_tock_v1_tick_tock_proto_rawDescGZIP(), []int{3}
}

func (x *TaskDefineReplyData) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tid           string                 `protobuf:"bytes,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Status        TaskDefineStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=helloworld.v1.TaskDefineStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_tick_tock_v1_tick_tock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tick_tock_v1_tick_tock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_tick_tock_v1_tick_tock_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *UpdateRequest) GetStatus() TaskDefineStatus {
	if x != nil {
		return x.Status
	}
	return TaskDefineStatus_TASK_DEFINE_STATUS_UNSPECIFIED
}

type UpdateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReply) Reset() {
	*x = UpdateReply{}
	mi := &file_api_tick_tock_v1_tick_tock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReply) ProtoMessage() {}

func (x *UpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_tick_tock_v1_tick_tock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReply.ProtoReflect.Descriptor instead.
func (*UpdateReply) Descriptor() ([]byte, []int) {
	return file_api_tick_tock_v1_tick_tock_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_tick_tock_v1_tick_tock_proto protoreflect.FileDescriptor

const file_api_tick_tock_v1_tick_tock_proto_rawDesc = "" +
	"\n" +
	" api/tick_tock/v1/tick_tock.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\xa3\x01\n" +
	"\rCreateRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fcron_expression\x18\x03 \x01(\tR\x0ecronExpression\x12C\n" +
	"\x12notify_http_params\x18\x04 \x01(\v2\x15.helloworld.v1.NotifyR\x10notifyHttpParams\"\x8e\x02\n" +
	"\x06Notify\x12\x19\n" +
	"\bhttp_url\x18\x01 \x01(\tR\ahttpUrl\x12\x1f\n" +
	"\vhttp_method\x18\x02 \x01(\tR\n" +
	"httpMethod\x12Y\n" +
	"\x12http_header_params\x18\x03 \x03(\v2+.helloworld.v1.Notify.HttpHeaderParamsEntryR\x10httpHeaderParams\x12(\n" +
	"\x10http_body_params\x18\x04 \x01(\tR\x0ehttpBodyParams\x1aC\n" +
	"\x15HttpHeaderParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\vCreateReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x04data\x18\x03 \x01(\v2\".helloworld.v1.TaskDefineReplyDataR\x04data\"'\n" +
	"\x13TaskDefineReplyData\x12\x10\n" +
	"\x03tid\x18\x01 \x01(\tR\x03tid\"Z\n" +
	"\rUpdateRequest\x12\x10\n" +
	"\x03tid\x18\x01 \x01(\tR\x03tid\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.helloworld.v1.TaskDefineStatusR\x06status\";\n" +
	"\vUpdateReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*u\n" +
	"\x10TaskDefineStatus\x12\"\n" +
	"\x1eTASK_DEFINE_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19TASK_DEFINE_STATUS_ENABLE\x10\x01\x12\x1e\n" +
	"\x1aTASK_DEFINE_STATUS_DISABLE\x10\x022\xfa\x01\n" +
	"\n" +
	"TickTocker\x12o\n" +
	"\x10CreateTaskDefine\x12\x1c.helloworld.v1.CreateRequest\x1a\x1a.helloworld.v1.CreateReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/tick-tock/task-define\x12{\n" +
	"\x16UpdateTaskDefineStatus\x12\x1c.helloworld.v1.UpdateRequest\x1a\x1a.helloworld.v1.UpdateReply\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/tick-tock/task-define/{tid}B\x1fZ\x1dtick-tock/api/tick-tock/v1;v1b\x06proto3"

var (
	file_api_tick_tock_v1_tick_tock_proto_rawDescOnce sync.Once
	file_api_tick_tock_v1_tick_tock_proto_rawDescData []byte
)

func file_api_tick_tock_v1_tick_tock_proto_rawDescGZIP() []byte {
	file_api_tick_tock_v1_tick_tock_proto_rawDescOnce.Do(func() {
		file_api_tick_tock_v1_tick_tock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tick_tock_v1_tick_tock_proto_rawDesc), len(file_api_tick_tock_v1_tick_tock_proto_rawDesc)))
	})
	return file_api_tick_tock_v1_tick_tock_proto_rawDescData
}

var file_api_tick_tock_v1_tick_tock_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_tick_tock_v1_tick_tock_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_tick_tock_v1_tick_tock_proto_goTypes = []any{
	(TaskDefineStatus)(0),       // 0: helloworld.v1.TaskDefineStatus
	(*CreateRequest)(nil),       // 1: helloworld.v1.CreateRequest
	(*Notify)(nil),              // 2: helloworld.v1.Notify
	(*CreateReply)(nil),         // 3: helloworld.v1.CreateReply
	(*TaskDefineReplyData)(nil), // 4: helloworld.v1.TaskDefineReplyData
	(*UpdateRequest)(nil),       // 5: helloworld.v1.UpdateRequest
	(*UpdateReply)(nil),         // 6: helloworld.v1.UpdateReply
	nil,                         // 7: helloworld.v1.Notify.HttpHeaderParamsEntry
}
var file_api_tick_tock_v1_tick_tock_proto_depIdxs = []int32{
	2, // 0: helloworld.v1.CreateRequest.notify_http_params:type_name -> helloworld.v1.Notify
	7, // 1: helloworld.v1.Notify.http_header_params:type_name -> helloworld.v1.Notify.HttpHeaderParamsEntry
	4, // 2: helloworld.v1.CreateReply.data:type_name -> helloworld.v1.TaskDefineReplyData
	0, // 3: helloworld.v1.UpdateRequest.status:type_name -> helloworld.v1.TaskDefineStatus
	1, // 4: helloworld.v1.TickTocker.CreateTaskDefine:input_type -> helloworld.v1.CreateRequest
	5, // 5: helloworld.v1.TickTocker.UpdateTaskDefineStatus:input_type -> helloworld.v1.UpdateRequest
	3, // 6: helloworld.v1.TickTocker.CreateTaskDefine:output_type -> helloworld.v1.CreateReply
	6, // 7: helloworld.v1.TickTocker.UpdateTaskDefineStatus:output_type -> helloworld.v1.UpdateReply
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_tick_tock_v1_tick_tock_proto_init() }
func file_api_tick_tock_v1_tick_tock_proto_init() {
	if File_api_tick_tock_v1_tick_tock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tick_tock_v1_tick_tock_proto_rawDesc), len(file_api_tick_tock_v1_tick_tock_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tick_tock_v1_tick_tock_proto_goTypes,
		DependencyIndexes: file_api_tick_tock_v1_tick_tock_proto_depIdxs,
		EnumInfos:         file_api_tick_tock_v1_tick_tock_proto_enumTypes,
		MessageInfos:      file_api_tick_tock_v1_tick_tock_proto_msgTypes,
	}.Build()
	File_api_tick_tock_v1_tick_tock_proto = out.File
	file_api_tick_tock_v1_tick_tock_proto_goTypes = nil
	file_api_tick_tock_v1_tick_tock_proto_depIdxs = nil
}
