server:
  http:
    addr: 0.0.0.0:33973
    timeout: 1s
  grpc:
    addr: 0.0.0.0:30771
    timeout: 1s
  task:
    tasks:
      - name: migrator
        type: cron
        schedule: "@every 1m"
      - name: scheduler
        type: once
#        首次触发的延迟时间
        schedule: "0s"
data:
  database:
    driver: mysql
    addr: 127.0.0.1:33060
    username: root
    password: root
    database: micro_tt
    max_open_conn: 10
    max_idle_conn: 10
#    proto duration 写法
    conn_max_idle_time: 60s
  redis:
    addr: 127.0.0.1:34701
    read_timeout: 0.2s
    write_timeout: 0.2s
  scheduler:
    poll_interval: 1s
    lock_duration: 70s
    lock_prefix: scheduler_lock_
    worker_poll_size: 100
    bucket_count: 1
  migrator:
    migrate_step: 1s
  trigger:
    poll_interval: 1s
    range_gap: 1s
    worker_pool_size: 100
